# Generated by Django 3.2 on 2024-11-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personajes', '0003_auto_20241025_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='arma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cantidad_balas', models.IntegerField(default=200, help_text='El número no debe ser menor a 200 balas')),
                ('tipo_bala', models.CharField(choices=[('9mm', '9mm'), ('calibre_45', 'calibre .45'), ('calibre_50', 'calibre .50')], max_length=50)),
                ('tipo_arma', models.CharField(choices=[('largo_alcanse', 'Largo Alcance'), ('medio_alcanse', 'Mediano Alcance'), ('baja_alcanse', 'Bajo Alcance')], max_length=50)),
                ('cadencia', models.CharField(choices=[('alto', 'Alto'), ('medio', 'Medio'), ('bajo', 'Bajo')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='caballo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('raza', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
                ('velocidad', models.CharField(choices=[('alta', 'alta'), ('media', 'media'), ('baja', 'baja')], max_length=5)),
                ('resistencia', models.CharField(choices=[('alta', 'alta'), ('media', 'media'), ('baja', 'baja')], max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='vaquero',
            name='apellido',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='vaquero',
            name='edad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vaquero',
            name='nombre',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='vaquero',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1),
        ),
        migrations.AddConstraint(
            model_name='vaquero',
            constraint=models.UniqueConstraint(fields=('id',), name='unique_vaquero'),
        ),
        migrations.AddField(
            model_name='vaquero',
            name='armas',
            field=models.ManyToManyField(related_name='vaqueros', to='personajes.arma'),
        ),
        migrations.AddField(
            model_name='vaquero',
            name='caballos',
            field=models.ManyToManyField(related_name='vaqueros', to='personajes.caballo'),
        ),
    ]
