# Generated by Django 3.2 on 2024-11-11 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personajes', '0005_auto_20241110_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arma',
            name='cantidad_balas',
            field=models.IntegerField(default=20, help_text='El número no debe ser menor a 20 balas'),
        ),
        migrations.AlterField(
            model_name='arma',
            name='vaquero',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arma_personal', to='personajes.vaquero'),
        ),
        migrations.AlterField(
            model_name='caballo',
            name='vaquero',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caballo_personal', to='personajes.vaquero'),
        ),
    ]
