# Generated by Django 3.2 on 2024-11-11 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personajes', '0006_auto_20241110_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaquero',
            name='arma',
            field=models.ManyToManyField(blank=True, related_name='vaqueros', to='personajes.arma'),
        ),
        migrations.AddField(
            model_name='vaquero',
            name='caballo',
            field=models.ManyToManyField(blank=True, related_name='vaqueros', to='personajes.caballo'),
        ),
    ]
