# Generated by Django 3.2 on 2024-11-11 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personajes', '0007_auto_20241110_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arma',
            name='tipo_arma',
            field=models.CharField(choices=[('largo_alcanse', 'Largo Alcance'), ('medio_alcanse', 'Mediano Alcance'), ('bajo_alcanse', 'Bajo Alcance')], max_length=50),
        ),
        migrations.AlterField(
            model_name='arma',
            name='vaquero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='armas', to='personajes.vaquero'),
        ),
        migrations.AlterField(
            model_name='caballo',
            name='vaquero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caballos', to='personajes.vaquero'),
        ),
    ]
