# Generated by Django 3.2 on 2024-11-12 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='arma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cantidad_balas', models.IntegerField(default=1, help_text='El número no debe ser menor a 1 balas')),
                ('tipo_bala', models.CharField(choices=[('9mm', '9mm'), ('calibre_45', 'calibre .45'), ('calibre_50', 'calibre .50')], max_length=50)),
                ('tipo_arma', models.CharField(choices=[('largo_alcanse', 'Largo Alcance'), ('medio_alcanse', 'Mediano Alcance'), ('bajo_alcanse', 'Bajo Alcance')], max_length=50)),
                ('cadencia', models.CharField(choices=[('alto', 'Alto'), ('medio', 'Medio'), ('bajo', 'Bajo')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='caballo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('raza', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
                ('velocidad', models.CharField(choices=[('alta', 'alta'), ('media', 'media'), ('baja', 'baja')], max_length=5)),
                ('resistencia', models.CharField(choices=[('alta', 'alta'), ('media', 'media'), ('baja', 'baja')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='vaquero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('edad', models.IntegerField(default=0)),
                ('buscado', models.BooleanField(default=False)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('arma', models.ManyToManyField(blank=True, related_name='vaqueros', to='personajes.arma')),
                ('caballo', models.ManyToManyField(blank=True, related_name='vaqueros', to='personajes.caballo')),
            ],
        ),
        migrations.AddField(
            model_name='caballo',
            name='vaquero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caballos', to='personajes.vaquero'),
        ),
        migrations.AddField(
            model_name='arma',
            name='vaquero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='armas', to='personajes.vaquero'),
        ),
    ]
