# Generated by Django 3.2 on 2024-10-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personajes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaquero',
            name='apellido',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='vaquero',
            name='nombre',
            field=models.CharField(max_length=25),
        ),
    ]
