# Generated by Django 3.2 on 2024-10-25 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personajes', '0002_auto_20241025_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaquero',
            name='apellido',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='vaquero',
            name='edad',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='vaquero',
            name='nombre',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='vaquero',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=10),
        ),
    ]
