# Generated by Django 3.2 on 2024-11-10 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personajes', '0004_auto_20241110_1229'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vaquero',
            name='unique_vaquero',
        ),
        migrations.RemoveField(
            model_name='vaquero',
            name='armas',
        ),
        migrations.RemoveField(
            model_name='vaquero',
            name='caballos',
        ),
        migrations.AddField(
            model_name='arma',
            name='vaquero',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arma_personal', to='personajes.vaquero'),
        ),
        migrations.AddField(
            model_name='caballo',
            name='vaquero',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caballo_personal', to='personajes.vaquero'),
        ),
    ]
